version: 2.1
orbs:
  slack: circleci/slack@4.10
jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          command: ./gradlew test
      - slack/notify:
          event: fail
          template: basic_fail_1
workflows:
  test_and_notify:
    jobs:
      - test:
          context: slack
